In [7]:
import numpy as np
import pandas as pd

In [18]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import OneHotEncoder

In [9]:
df = pd.read_csv("../Azure-ML/dataset/training.csv")

In [10]:
df

Food_item  Mass Burner_size  simTime  onTime  on_offTime  on_simTime  \
0           Tea   600      medium        5       2           0           0   
1          Milk  1000      medium        0       5           0          10   
2          Idli   500      medium        7       8           0           0   
3         Water   200      medium        5       3           2           1   
4  Chicken soup   500      medium       20       0           0           0   
5         Water   200       small        7       4           3           2   

   order0  order1  order2  order3  
0       1       0      -1      -1  
1      -1       0      -1       1  
2       1       0      -1      -1  
3       0       1       2       3  
4       0      -1      -1      -1  
5       0       1       2       3

In [11]:
X = df.iloc[:,:3].values
y = df.iloc[:,3:6].values

In [51]:
unique_foodItems = np.unique(X[:,0])
unique_burnerSizes = np.array(["small", "medium", "large"])

In [52]:
labelencoder1 = LabelEncoder()
labelencoder2= LabelEncoder()

labelencoder1.fit(unique_foodItems)
X[:, 0] = labelencoder1.transform(X[:,0])

labelencoder2.fit(unique_burnerSizes)

X[:, 2] = labelencoder2.transform(X[:, 2])

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [32]:
dTf = DecisionTreeRegressor()

In [33]:
dTf.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [37]:
y_train_pred = dTf.predict(y_train)

In [43]:
y_train_pred

array([[5., 3., 2.],
       [5., 3., 2.],
       [5., 3., 2.]])

In [40]:
y_train

array([[5, 2, 0],
       [7, 8, 0],
       [5, 3, 2]])

In [44]:
X_train

array([[3, 600, 0],
       [1, 500, 0],
       [4, 200, 0]], dtype=object)

In [20]:
from sklearn.preprocessing import OneHotEncoder
onehotencoder = OneHotEncoder(categorical_features = [0,2])
X_train_oneHot = onehotencoder.fit_transform(X_train).toarray()
X_test_oneHot = onehotencoder.transform(X_test).toarray()

/home/arshad/anaconda2/envs/py36/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:363: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/arshad/anaconda2/envs/py36/lib/python3.6/site-packages/sklearn/preprocessing/_encoders.py:385: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [21]:
X_train_oneHot

array([[   0.,    0.,    1.,    0.,    1.,    0.,  600.],
       [   0.,    1.,    0.,    0.,    1.,    0., 1000.],
       [   0.,    0.,    0.,    1.,    0.,    1.,  200.],
       [   1.,    0.,    0.,    0.,    1.,    0.,  500.]])

In [22]:
X_test_oneHot

array([[  0.,   0.,   0.,   1.,   1.,   0., 200.],
       [  0.,   0.,   0.,   0.,   1.,   0., 500.]])

In [103]:
dTf = DecisionTreeRegressor()

In [104]:
dTf.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [108]:
y_train_pred = dTf.predict(y_train)
y_test_pred = dTf.predict(y_test)

In [106]:
y_train_pred

array([[5., 2., 0.],
       [5., 2., 0.],
       [5., 2., 0.],
       [7., 4., 3.]])

In [107]:
y_train

array([[ 5,  2,  0],
       [20,  0,  0],
       [ 7,  8,  0],
       [ 7,  4,  3]])

In [109]:
y_test_pred

array([[20.,  0.,  0.],
       [ 7.,  4.,  3.]])

In [110]:
y_test

array([[0, 5, 0],
       [5, 3, 2]])

In [111]:
X_test[0]

array([2, 1000, 0], dtype=object)

In [12]:
from sklearn.linear_model import LinearRegression

In [55]:
lr = LinearRegression()

In [56]:
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [57]:
y_train_pred = lr.predict(X_train)

In [58]:
y_train_pred[0][1]

2.333333333333333

In [30]:
rmse(y_train, y_train_pred)

NameError: name 'rmse' is not defined

In [59]:
from sklearn.metrics import mean_squared_error as mse

In [60]:
mse(y_train, y_train_pred)

0.6249999999999998

In [61]:
y_train

array([[ 5,  3,  2],
       [20,  0,  0],
       [ 5,  2,  0],
       [ 0,  5,  0]])

In [62]:
y_train_pred

array([[ 5.83333333,  2.33333333,  1.66666667],
       [20.        ,  0.        ,  0.        ],
       [ 3.33333333,  3.33333333,  0.66666667],
       [ 0.83333333,  4.33333333, -0.33333333]])

In [63]:
y_train_pred[3][0]

0.8333333333333357

In [64]:
y_test_pred = lr.predict(X_test)

In [65]:
y_test_pred

array([[ 5.83333333,  2.33333333,  1.66666667],
       [15.06410256,  0.94871795,  0.28205128]])

In [66]:
y_test

array([[7, 4, 3],
       [7, 8, 0]])

In [67]:
y_test[0][0]

7

In [68]:
y_test_pred[0][2]

1.666666666666667

In [70]:
mse(y_test, y_test_pred)

20.12442472057857

In [101]:
toPred = np.array(["Tea", 330, "medium"])

In [102]:
toPred[0] = (labelencoder1.transform([toPred[0]]))[0]
toPred[2] = (labelencoder2.transform([toPred[2]]))[0]

In [108]:
y_pred = onehotencoder.transform(toPred.reshape(1,-1)).toarray()

In [109]:
lr.predict(y_pred)

ValueError: shapes (1,7) and (3,3) not aligned: 7 (dim 1) != 3 (dim 0)

In [79]:
X_train[:,2]

array([1, 1, 1, 1], dtype=object)

In [89]:
a = [toPred[0]]

In [84]:
np.array(toPred[0])

array('Tea', dtype='<U3')

In [37]:
class ModifiedLabelEncoder(LabelEncoder):
    def __init__(self):
        self.le = LabelEncoder()

    def fit_transform(self, y, *args, **kwargs):
        return self.le.fit_transform(y).reshape(-1, 1)

    def transform(self, y, *args, **kwargs):
        return self.le.transform(y).reshape(-1, 1)

In [28]:
le = LabelEncoder()
ohe = OneHotEncoder()

In [112]:
pipe = Pipeline([("le", ModifiedLabelEncoder()), ("ohe", OneHotEncoder())])
pipe.fit_transform(X[:,0])

NameError: name 'Pipeline' is not defined

In [38]:
# from sklearn2pmml.Pipeline import PMMLPipeline
from sklearn2pmml import PMMLPipeline

pipeline = PMMLPipeline([
    ("le", ModifiedLabelEncoder()), 
    ("ohe", OneHotEncoder()),
    ("regressor", LinearRegression())
])
pipeline.fit(X_train, y_train)

from sklearn2pmml import sklearn2pmml

sklearn2pmml(pipeline, "lr.pmml", with_repr = True)

ValueError: bad input shape (4, 3)

In [1]:
import sklearn, sklearn.externals.joblib, sklearn_pandas, sklearn2pmml

print(sklearn.__version__)
print(sklearn.externals.joblib.__version__)
print(sklearn_pandas.__version__)
print(sklearn2pmml.__version__)

0.20.1
0.13.0
1.3.4
0.20.2


In [3]:
from sklearn.pipeline import Pipeline

In [ ]:
sklearn2pmml.P